openapi: 3.0.3
info:
  title: STD23000 - TD1
  version: '1.0.1'
servers:
  - url: https://localhost.std230xxx.com
paths:
  /customers:
    get:
      parameters:
        - name: page
          description: page number
          in: query
          required: true
          schema:
            type: integer
        - name: pageSize
          description: showing page size
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: "create client list"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
              properties:
                name: 
                  type: string
                  example: "Rakoto"
                age:
                  type: integer
                  example: 18
      responses: 
        '200':
          description: "client created with success"
          content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: "Rakoto"
                      age:
                        type: integer
                        example: 18
     delete:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CustomerIdentifier'
        required: true
      responses:
        200:
          description: List of deleted customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer